name: Decont
description: "Simplify Buying."

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  geolocator: ^10.1.0
  permission_handler: ^11.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  package_info_plus: ^5.0.1
  custom_rating_bar: ^3.0.0
  webview_flutter: ^4.5.0
  get: ^4.6.5
  flutter_html: ^3.0.0-alpha.1
  cached_network_image: ^3.2.3
  flutter_file_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.8
  http: ^1.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_svg: ^1.0.3
  pinput: ^2.2.31
  url_launcher: ^6.1.7
  path_provider: ^2.0.11
  flutter_rating_bar: ^4.0.0
  social_sharing_plus: ^1.2.3
  lottie: ^2.0.0
  speech_to_text: ^6.5.1
  photo_view: ^0.15.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  razorpay_flutter: ^1.4.0
  share_plus: ^7.2.2



change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.4.0



flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/app_icon_image/app_icon.png"
  image_path_ios: "assets/app_icon_image/app_icon.png"


flutter:


  uses-material-design: true


  assets:
    - assets/decont_splash_screen_images/
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/animations/
    - assets/decont_drawer/
    - assets/payment_method_screen/

  fonts:
    - family: GraphikRegular
      fonts:
        - asset: fonts/GraphikRegular.otf

    - family: GraphikMedium
      fonts:
        - asset: fonts/GraphikMedium.otf

    - family: GraphikSemibold
      fonts:
        - asset: fonts/GraphikSemibold.otf

    - family: GraphikBold
      fonts:
        - asset: fonts/GraphikBold.otf

